# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: video_process_count.py
import os
import threading
from pathlib import Path
from typing import Dict, List, Optional
import time 
import cv2
import numpy as np
from ultralytics import YOLO

VEHICLE_CLASSES = {2: "car", 5: "bus", 7: "truck"}
REGION_COLORS = [(0, 255, 0), (255, 0, 0), (0, 255, 255), (255, 255, 0)]

_MODEL_CACHE: Dict[str, YOLO] = {}
_MODEL_LOCK = threading.Lock()
_INFER_LOCK = threading.Lock()


def clamp_points(points: np.ndarray, width: int, height: int) -> np.ndarray:
    pts = points.copy()
    pts[:, 0] = np.clip(pts[:, 0], 0, width - 1)
    pts[:, 1] = np.clip(pts[:, 1], 0, height - 1)
    return pts.astype(np.int32)


def build_regions(regions: Optional[dict], width: int, height: int) -> List[dict]:
    if not isinstance(regions, dict):
        return []
    parsed = []
    for idx, (name, pts) in enumerate(regions.items()):
        arr = np.array(pts, dtype=np.int32)
        if arr.ndim != 2 or arr.shape[1] != 2:
            continue
        parsed.append(
            {
                "name": str(name),
                "points": clamp_points(arr, width, height),
                "color": REGION_COLORS[idx % len(REGION_COLORS)],
            }
        )
    return parsed


class VideoProcessCount:
    def __init__(self, model_path: str = "yolov8m.pt", conf_threshold: float = 0.25, iou_threshold: float = 0.45):
        self.model_path = model_path
        self.conf_threshold = conf_threshold
        self.iou_threshold = iou_threshold

    def _get_model(self) -> YOLO:
        with _MODEL_LOCK:
            model = _MODEL_CACHE.get(self.model_path)
            if model is None:
                model = YOLO(self.model_path)
                _MODEL_CACHE[self.model_path] = model
        return model

    def _read_frame_at_second(self, cap: cv2.VideoCapture, fps: float, sec: float):
        targets = [float(sec), max(0.0, sec - 0.2), max(0.0, sec - 0.5), max(0.0, sec - 1.0)]
        for target in targets:
            cap.set(cv2.CAP_PROP_POS_MSEC, target * 1000.0)
            ok, frame = cap.read()
            if ok and frame is not None:
                return frame
            if fps > 0:
                cap.set(cv2.CAP_PROP_POS_FRAMES, int(target * fps))
                ok, frame = cap.read()
                if ok and frame is not None:
                    return frame
        return None

    def _count_frame(self, frame: np.ndarray, regions: List[dict] , output_dir: Optional[str] = None,cam_id: Optional[str] = None) -> (int, Dict[str, int], List[dict], Optional[str]):
        model = self._get_model()
        with _INFER_LOCK:
            results = model.predict(
                source=frame,
                conf=self.conf_threshold,
                iou=self.iou_threshold,
                classes=list(VEHICLE_CLASSES.keys()),
                verbose=False,
            )
 
        total_count = 0
        region_counts = {region["name"]: 0 for region in regions}
        detections = []
 
        boxes = results[0].boxes
        if boxes is None:
            return total_count, region_counts, detections
 
        for box in boxes:
            cls_id = int(box.cls[0].item())
            if cls_id not in VEHICLE_CLASSES:
                continue
 
            conf = float(box.conf[0].item())
            x1, y1, x2, y2 = map(int, box.xyxy[0].tolist())
            cx = (x1 + x2) // 2
            cy = (y1 + y2) // 2
 
            region_name = None
            color = (0, 0, 255)
 
            if regions:
                for region in regions:
                    if cv2.pointPolygonTest(region["points"], (cx, cy), False) >= 0:
                        region_name = region["name"]
                        region_counts[region_name] += 1
                        color = region["color"]
                        total_count += 1
                        break
                if region_name is None:
                    continue
            else:
                total_count += 1
 
            label = f"{VEHICLE_CLASSES[cls_id]} {conf:.2f}"
            if region_name:
                label = f"{label} | {region_name}"
 
            detections.append(
                {
                    "box": (x1, y1, x2, y2),
                    "center": (cx, cy),
                    "label": label,
                    "color": color,
                }
            )
        # height, width = frame.shape[:2]
        # parsed_regions = build_regions(regions, width, height)
 
        frame_path = self._save_annotated_frame(frame, 0, total_count, detections, regions, output_dir,cam_id)
 
        return total_count, region_counts, detections , frame_path

    def _save_annotated_frame(
        self,
        frame: np.ndarray,
        second_mark: int,
        count: int,
        detections: List[dict],
        regions: List[dict],
        output_dir: str,
        cam_id: Optional[str] = None,
    ) -> str:
        annotated = frame.copy()

        for region in regions:
            print(f"Drawing region: {region['name']} with color {region['color']}")
            overlay = annotated.copy()
            cv2.fillPoly(overlay, [region["points"]], region["color"])
            cv2.addWeighted(overlay, 0.16, annotated, 0.84, 0, annotated)
            cv2.polylines(annotated, [region["points"]], True, region["color"], 2)
            x, y, _, _ = cv2.boundingRect(region["points"])
            cv2.putText(annotated, region["name"], (x, max(25, y - 10)), cv2.FONT_HERSHEY_SIMPLEX, 0.7, region["color"], 2)

        for det in detections:
            x1, y1, x2, y2 = det["box"]
            cx, cy = det["center"]
            color = det["color"]
            cv2.rectangle(annotated, (x1, y1), (x2, y2), color, 2)
            cv2.circle(annotated, (cx, cy), 4, color, -1)
            cv2.putText(annotated, det["label"], (x1, max(20, y1 - 8)), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

        cv2.putText(annotated, f"second={second_mark} count={count}", (10, 25), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 255, 255), 2)
        output_dir = os.path.join(output_dir, cam_id)
        Path(output_dir).mkdir(parents=True, exist_ok=True)
        out_path = os.path.join(output_dir, f"second_{time.time():.0f}.jpg")
        cv2.imwrite(out_path, annotated)
        return out_path

    def process_video(
        self,
        video_path: str,
        interval_seconds: int = 1,
        regions: Optional[dict] = None,
        save_annotated_frames: bool = False,
        save_output_dir: Optional[str] = None,
    ) -> dict:
        if not os.path.isfile(video_path):
            return {"video_path": video_path, "error": f"Video file not found: {video_path}"}

        cap = cv2.VideoCapture(video_path)
        if not cap.isOpened():
            cap.release()
            return {"video_path": video_path, "error": "Could not open video file"}

        try:
            fps = float(cap.get(cv2.CAP_PROP_FPS) or 0.0)
            frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
            width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH) or 1920)
            height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT) or 1080)
            duration_seconds = (frame_count / fps) if fps > 0 and frame_count > 0 else 0.0
            parsed_regions = build_regions(regions, width, height)

            saved_frames = []
            output_dir = None
            if save_annotated_frames:
                base_dir = save_output_dir or os.path.join(os.path.dirname(video_path), "video_counts_debug")
                output_dir = os.path.join(base_dir, Path(video_path).stem)

            if duration_seconds <= 0 or duration_seconds < interval_seconds:
                frame = self._read_frame_at_second(cap, fps, 0.0)
                if frame is None:
                    return {"video_path": video_path, "error": "Could not decode a frame from video"}

                count, _, detections = self._count_frame(frame, parsed_regions)
                if output_dir:
                    frame_path = self._save_annotated_frame(frame, 0, count, detections, parsed_regions, output_dir)
                    saved_frames.append({"second": 0, "path": frame_path, "count": count})

                result = {
                    "video_path": video_path,
                    "model_path": self.model_path,
                    "duration_seconds": round(float(duration_seconds), 3),
                    "confidence_threshold": self.conf_threshold,
                    "count": int(count),
                }
            else:
                marks = list(range(interval_seconds, int(duration_seconds) + 1, interval_seconds))
                counts = []

                for sec_mark in marks:
                    seek_second = min(float(sec_mark), max(0.0, float(duration_seconds) - 0.05))
                    frame = self._read_frame_at_second(cap, fps, seek_second)
                    if frame is None:
                        continue

                    count, _, detections = self._count_frame(frame, parsed_regions)
                    counts.append({"second": int(sec_mark), "count": int(count)})

                    if output_dir:
                        frame_path = self._save_annotated_frame(frame, sec_mark, count, detections, parsed_regions, output_dir)
                        saved_frames.append({"second": int(sec_mark), "path": frame_path, "count": int(count)})

                if not counts:
                    return {"video_path": video_path, "error": "Could not decode sampled frames from video"}

                result = {
                    "video_path": video_path,
                    "model_path": self.model_path,
                    "duration_seconds": round(float(duration_seconds), 3),
                    "interval_seconds": int(interval_seconds),
                    "confidence_threshold": self.conf_threshold,
                    "counts": counts,
                }

            if output_dir:
                result["saved_output_dir"] = output_dir
                result["saved_frames"] = saved_frames

            return result
        finally:
            cap.release()
